version: '3.7'

services: 
  rabbitmq: 
    image: rabbitmq:management
    ports: 
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_VHOST=myvhost
